name: 'PyPi-like publish'
description: 'Publish Python packages to pypi repository via artifacts using twine'
author: 'Fabien Ors'

inputs:
  repo:
    description: 'The repository ('pypi' or 'testpypi')
    default: "pypi"
  username:
    description: 'Username for the repository'
    default: "__token__"
  password:
    description: 'Password for the repository'
  pattern:
    description: 'File name pattern filter'
    default: "*"
    
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      # Downloading several artifacts:
      # https://github.com/actions/download-artifact/issues/103#issuecomment-1290368250
      with:
        path: download_artifacts

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install twine

    - name: Upload Python packages (all artifacts)
      # For join_by function: https://stackoverflow.com/a/17841619/3952924
      run : python -m twine upload download_artifacts/*/${{ inputs.pattern }}
      env:
        TWINE_USERNAME: ${{ inputs.username }}
        TWINE_PASSWORD: ${{ inputs.password }}
        TWINE_REPOSITORY: ${{ inputs.repo }}
      shell: bash


